"""empty message

Revision ID: aeda29d8eba3
Revises: 7c123273c471
Create Date: 2025-07-29 14:22:34.573227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeda29d8eba3'
down_revision = '7c123273c471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_header',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('rate_euro', sa.Float(), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_detail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value_idr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_category_id'], ['ms_category.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_detail')
    op.drop_table('transaction_header')
    op.drop_table('ms_category')
    # ### end Alembic commands ###
